/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false server/types/worker-configuration.d.ts` (hash: 4efcec1ac3cb4a6baff974c437b6f85e)
interface __BaseEnv_Env {
	DB: D1Database;
	MATCH_ROOMS: DurableObjectNamespace /* MatchRoom from mind-boggling-match-room */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
