<script setup lang="ts">
import type { FarkleSettings } from '../../../shared/games/farkle'

const toast = useToast()
const submitting = shallowRef(false)
const matchName = shallowRef('Family Farkle night')
const settings = reactive<FarkleSettings>({ rulesVersion: 'classic.v1', targetScore: 10000, locale: 'en-US' })
const targetOptions = [
  { value: 1000 as const, label: '1,000', description: 'A quick, high-pressure match.' },
  { value: 5000 as const, label: '5,000', description: 'A balanced game-night length.' },
  { value: 10000 as const, label: '10,000', description: 'The full classic game.' }
]

async function submit() {
  submitting.value = true
  try {
    const result = await $fetch<{ matchId: string, inviteUrl: string }>('/api/matches', {
      method: 'POST',
      body: { gameKey: 'farkle.v1', name: matchName.value, settings }
    })
    sessionStorage.setItem(`mind-boggling:invite:${result.matchId}`, result.inviteUrl)
    await navigateTo(`/matches/${result.matchId}`)
  } catch (error) {
    toast.add({ title: 'Match not created', description: error instanceof Error ? error.message : 'Try again.', color: 'error' })
  } finally {
    submitting.value = false
  }
}
</script>

<template>
  <div class="mx-auto max-w-[1120px] px-5 py-9 sm:px-8 lg:px-12 lg:py-12">
    <UButton
      to="/"
      color="neutral"
      variant="ghost"
      icon="i-lucide-arrow-left"
      class="-ml-3 mb-5"
    >
      Back to games
    </UButton>
    <div class="mb-8">
      <UBadge variant="soft">
        Farkle · classic.v1
      </UBadge>
      <h1 class="mt-3 font-display text-4xl font-extrabold tracking-tight">
        Set the stakes.
      </h1>
      <p class="mt-2 max-w-2xl text-slate-600">
        Choose the finish line. The scoring table, 500-point entry, hot dice, and sudden death stay fixed.
      </p>
    </div>

    <div class="grid gap-6 lg:grid-cols-[1fr_22rem]">
      <form
        class="game-panel rounded-xl p-6 sm:p-8"
        @submit.prevent="submit"
      >
        <UFormField
          label="Match name"
          required
        >
          <UInput
            v-model="matchName"
            maxlength="48"
            size="lg"
            class="w-full"
          />
        </UFormField>

        <fieldset class="mt-7 border-t border-slate-200 pt-5">
          <legend class="font-display text-xl font-bold">
            Winning score
          </legend>
          <p class="mt-1 text-sm text-slate-500">
            Every other player gets one final turn after someone reaches this score.
          </p>
          <div class="mt-4 grid gap-3 sm:grid-cols-3">
            <button
              v-for="option in targetOptions"
              :key="option.value"
              type="button"
              :aria-pressed="settings.targetScore === option.value"
              class="rounded-xl border p-4 text-left transition"
              :class="settings.targetScore === option.value ? 'border-2 border-primary-600 bg-primary-50' : 'border-slate-200 bg-slate-50 hover:border-slate-400'"
              @click="settings.targetScore = option.value"
            >
              <span class="block font-mono text-2xl font-black">{{ option.label }}</span>
              <span class="mt-1 block text-xs text-slate-500">{{ option.description }}</span>
            </button>
          </div>
        </fieldset>

        <div class="mt-7 flex flex-col items-start justify-between gap-4 border-t border-slate-200 pt-5 sm:flex-row sm:items-center">
          <p class="text-xs text-slate-500">
            <UIcon
              name="i-lucide-shield-check"
              class="mr-1 inline size-4"
            />Rolls are generated by the authoritative game room.
          </p>
          <UButton
            type="submit"
            size="lg"
            trailing-icon="i-lucide-arrow-right"
            :loading="submitting"
          >
            Create private match
          </UButton>
        </div>
      </form>

      <aside class="rounded-xl bg-slate-950 p-6 text-white">
        <div class="flex items-center justify-between">
          <p class="font-display text-xl font-bold">
            Classic table
          </p>
          <UIcon
            name="i-lucide-dices"
            class="size-6 text-primary-300"
          />
        </div>
        <div
          class="mt-6 grid grid-cols-3 gap-3"
          aria-hidden="true"
        >
          <span
            v-for="face in 6"
            :key="face"
            class="grid aspect-square place-items-center rounded-xl bg-white font-mono text-3xl font-black text-slate-950 shadow"
          >{{ face }}</span>
        </div>
        <dl class="mt-6 space-y-3 text-sm">
          <div class="flex justify-between">
            <dt class="text-slate-400">
              Players
            </dt><dd class="font-mono font-bold">
              2–8
            </dd>
          </div>
          <div class="flex justify-between">
            <dt class="text-slate-400">
              Entry
            </dt><dd class="font-mono font-bold">
              500 pts
            </dd>
          </div>
          <div class="flex justify-between">
            <dt class="text-slate-400">
              Three 1s
            </dt><dd class="font-mono font-bold">
              300 pts
            </dd>
          </div>
          <div class="flex justify-between">
            <dt class="text-slate-400">
              Hot dice
            </dt><dd class="font-mono font-bold">
              On
            </dd>
          </div>
          <div class="flex justify-between">
            <dt class="text-slate-400">
              Disconnected turn
            </dt><dd class="font-mono font-bold">
              Skip at 60s
            </dd>
          </div>
        </dl>
      </aside>
    </div>
  </div>
</template>
