/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/match-room/wrangler.jsonc --include-runtime=false workers/match-room/worker-configuration.d.ts` (hash: c905b235236f647723a6a3e0a5d653f4)
interface __BaseEnv_Env {
	DB: D1Database;
	MATCH_ROOMS: DurableObjectNamespace<import("./src/index").MatchRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MatchRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
